version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  userservice:
    container_name: userservice
    build: .
    image: userservice-image
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: always